/**
 * One export from the predecessor, in the shape it actually writes.
 *
 * Generated by running the predecessor's own `session_to_profile()` over its
 * factory profile and then editing the scalars to look like somebody's rather
 * than the factory's — so the key spelling, the flat structure and the integer
 * percentages are the real ones rather than this repo's idea of them.
 *
 * `pdf_layout` is here because the file has it, not because anything reads it.
 */
export const PREDECESSOR_EXPORT: Record<string, unknown> = {
  "weight_kg": 82.5,
  "height_cm": 178,
  "age": 34,
  "sex_label": "Masculino",
  "activity_idx": 2,
  "kcal_adjustment": -500,
  "coeff_protein": 2.2,
  "coeff_carb": 3.4,
  "coeff_fat": 0.9,
  "pdf_layout": "Tabela",
  "use_custom_fa": false,
  "custom_fa": 1.4,
  "dist_treino_carb_0": 20,
  "dist_treino_carb_1": 30,
  "dist_treino_carb_2": 10,
  "dist_treino_carb_3": 40,
  "dist_treino_protein_0": 25,
  "dist_treino_protein_1": 25,
  "dist_treino_protein_2": 15,
  "dist_treino_protein_3": 35,
  "dist_treino_fat_0": 20,
  "dist_treino_fat_1": 30,
  "dist_treino_fat_2": 15,
  "dist_treino_fat_3": 35,
  "dist_descanso_carb_0": 18,
  "dist_descanso_carb_1": 27,
  "dist_descanso_carb_2": 12,
  "dist_descanso_carb_3": 43,
  "dist_descanso_protein_0": 25,
  "dist_descanso_protein_1": 25,
  "dist_descanso_protein_2": 15,
  "dist_descanso_protein_3": 35,
  "dist_descanso_fat_0": 20,
  "dist_descanso_fat_1": 30,
  "dist_descanso_fat_2": 15,
  "dist_descanso_fat_3": 35,
  "descanso_carb_cut_0": 0,
  "descanso_carb_cut_1": 15,
  "descanso_carb_cut_2": 0,
  "descanso_carb_cut_3": 0,
  "sel_treino_carb_0": 1,
  "sel_treino_carb_1": 0,
  "sel_treino_carb_2": 0,
  "sel_treino_carb_3": 0,
  "sel_treino_prot_0": 0,
  "sel_treino_prot_1": 2,
  "sel_treino_prot_2": 0,
  "sel_treino_prot_3": 0,
  "sel_descanso_carb_0": 0,
  "sel_descanso_carb_1": 0,
  "sel_descanso_carb_2": 0,
  "sel_descanso_carb_3": 3,
  "sel_descanso_prot_0": 0,
  "sel_descanso_prot_1": 0,
  "sel_descanso_prot_2": 0,
  "sel_descanso_prot_3": 0
};
